###
GET http://localhost:3001/api/v1/posts
###

GET http://localhost:3001/api/v1/posts/32
###

DELETE http://localhost:3001/api/v1/posts/1
###

POST http://localhost:3001/api/v1/posts
Content-Type: application/json

{
    "title": "Weekend Hike",
    "body": "Hiked to the top of the mountain this weekend. The view was totally worth it!",
    "tags": ["hiking", "outdoors", "fitness"],
    "reactions": {
        "likes": 450,
        "dislikes": 1
    },
    "views": 1000,
    "userId": 230,
    "imageUrl": "https://images.pexels.com/photos/1365425/pexels-photo-1365425.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "timestamp": "2024-09-10T14:23:00",
    "duration": 180
}
